domain: cefunck.github.io/LeafyWebsite       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cefunck.github.io/LeafyWebsite  # the base hostname and protocol for your site, e.g. http://example.com

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
